{
    'name': 'Engineering_Project_Management',
    'version': '1.0',
    'category': 'Project',
    'summary': 'Add additional project management features',
    'description': 'This module adds additional fields and features to the project management module.',
    'author': 'Lidefend',
    'depends': ['project'],
    'data': [ 'security/ir.model.access.csv',
              'views/project_views.xml',
              'views/plan_views.xml',
              'views/cost_views.xml',
              'views/quality_views.xml',
              'views/safety_views.xml',
              'views/menus.xml',
              'report/reports.xml',
              ],
    #'post_init_hook': '_project_post_init',
    'installable': True,
    'application': True,
}