services:
  odoo:
    build: .
    container_name: odoo17
    command: --config=/etc/odoo/odoo.conf
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=123456
      - DB_NAME=odoo17
      - ODOO_JWT_SECRET=my_super_secure_token_123456
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./odoo_data:/var/lib/odoo
      - ./odoo_filestore:/opt/odoo-data  # ⬅️ 专门挂 filestore
    networks:
      - odoo17_network

  nginx:
    image: nginx:latest
    container_name: nginx_odoo
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - odoo
    networks:
      - odoo17_network

volumes:
  odoo_data:
  odoo_filestore:

networks:
  odoo17_network:
    driver: bridge
